model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: azure/tripknow35
      api_base: https://tripknowproduction1.openai.azure.com/
      api_key: "os.environ/AZURE_API_KEY"
      api_version: "2023-08-01-preview"
  - model_name: gpt-4-turbo
    litellm_params:
      model: azure/tripknow4
      api_base: https://tripknowproduction1.openai.azure.com/
      api_key: "os.environ/AZURE_API_KEY"
      api_version: "2023-08-01-preview"

litellm_settings:
  drop_params: True
  set_verbose: True

general_settings: 
  # master_key: sk-1234 # [OPTIONAL] Only use this if you to require all calls to contain this key (Authorization: Bearer sk-1234)
  # database_url: "postgresql://<user>:<password>@<host>:<port>/<dbname>" # [OPTIONAL] use for token-based auth to proxy

environment_variables:
  # settings for using redis caching
  # REDIS_HOST: redis-16337.c322.us-east-1-2.ec2.cloud.redislabs.com
  # REDIS_PORT: "16337"
  # REDIS_PASSWORD: 
